services:
  node-1:
    image: laboratory-4
    container_name: laboratory-4-1
    ports:
      - "127.0.0.100:9090:9090"
    networks:
      - laboratory-4
  node-2:
    image: laboratory-4
    container_name: laboratory-4-2
    ports:
      - "127.0.0.101:9090:9090"
    networks:
      - laboratory-4
    depends_on:
      - node-1
    links:
      - node-1
  node-3:
    image: laboratory-4
    container_name: laboratory-4-3
    ports:
      - "127.0.0.102:9090:9090"
    networks:
      - laboratory-4
    depends_on:
      - node-2
    links:
      - node-2

networks:
  laboratory-4:
    driver: bridge
