version: '3.8'
networks:
  laboratory-1-network:
    driver: bridge

services:
  laboratory-1-db-1:
    image: cassandra:latest
    container_name: laboratory-1-db-1
    networks:
      - laboratory-1-network
    ports:
      - "9042:9042"
    environment: &cassandra_environment
      CASSANDRA_SEEDS: laboratory-1-db-1
      CASSANDRA_CLUSTER_NAME: laboratory-1-cluster
      CASSANDRA_DC: laboratory-1-datacenter
      CASSANDRA_NUM_TOKENS: 256
      CASSANDRA_RACK: rack1
    restart:
      on-failure
    healthcheck: &healthcheck
      test: [ "CMD-SHELL", "nodetool status" ]
      interval: 2s
      start_period: 10s
      timeout: 2s
      retries: 120

  laboratory-1-db-2:
    image: cassandra:latest
    container_name: laboratory-1-db-2
    networks:
      - laboratory-1-network
    ports:
      - "9043:9042"
    environment: *cassandra_environment
    restart:
      on-failure
    depends_on:
      laboratory-1-db-1:
        condition: service_healthy
    healthcheck: *healthcheck

  laboratory-1-main:
    build:
      context: .
    container_name: laboratory-1-main
    image: laboratory-1-main
    networks:
      - laboratory-1-network
    ports:
      - "9090:9090"
    restart:
      on-failure
    environment:
      CASSANDRA_CONTACT_POINTS: "laboratory-1-db-1:9042 laboratory-1-db-2:9043"
    depends_on:
      laboratory-1-db-2:
        condition: service_healthy
